NumPy

In [1]:
#Create Different Types of NumPy Arrays (1D, 2D, 3D)
import numpy as np

# Create a 1D array (just a list of numbers)
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# Create a 2D array (2 rows, 3 columns)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# Create a 3D array (2 blocks, each with 2 rows and 2 columns)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
#Perform Basic Arithmetic Operations on Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add arrays (element-wise)
result_add = arr1 + arr2
print(result_add)


# Subtract arrays (element-wise)
result_sub = arr1 - arr2
print(result_sub)

# Multiply arrays (element-wise)
result_mul = arr1 * arr2
print(result_mul)


# Divide arrays (element-wise)
result_div = arr2 / arr1
print(result_div)



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]


In [5]:
#Use Indexing and Slicing to Access Elements
arr = np.array([10, 20, 30, 40, 50])

# Get the first element (index 0)
print(arr[0])

# Get the last element (index -1)
print(arr[-1])

# Get elements from index 1 to 3 (not including 3)
print(arr[1:3])

# Get elements from index 2 to the end
print(arr[2:])

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Get the value at row 1, column 2
print(arr_2d[1, 2])

# Get the entire second row
print(arr_2d[1, :])  # Output: [4 5 6]

# Get the first two columns of both rows
print(arr_2d[:, :2])

10
50
[20 30]
[30 40 50]
6
[4 5 6]
[[1 2]
 [4 5]]


In [7]:
#Explore Array Manipulation Functions
arr = np.array([0, 1, 2, 3, 4, 5])

# Change the 1D array into a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Transpose (flip rows and columns)
transposed_arr = arr_2d.T
print(transposed_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate (join) arrays
concat_arr = np.concatenate((arr1, arr2))
print(concat_arr)


[[0 1 2]
 [3 4 5]]
[[1 3 5]
 [2 4 6]]
[1 2 3 4 5 6]


In [9]:
#Create and Use NumPy Random Number Generators
# Generate 5 random numbers between 0 and 1
random_numbers = np.random.rand(5)
print(random_numbers)

# Generate 5 random integers between 1 and 10
random_integers = np.random.randint(1, 10, size=5)
print(random_integers)

# Set seed so that the random numbers will always be the same
np.random.seed(42)
random_numbers = np.random.rand(5)
print(random_numbers)

[0.07040674 0.42461242 0.7021726  0.21421365 0.65472929]
[4 1 9 6 5]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
